version: '3'

services:
  avalon:
    build: .
    environment:
      DB_URL: mongodb://mongodb:27017
      NODE_OWNER_PUB: ${NODE_OWNER_PUB}
      NODE_OWNER_PRIV: ${NODE_OWNER_PRIV}
      NODE_OWNER: ${NODE_OWNER}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
      - 6001:6001
    restart: unless-stopped
    command: npm run start:docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    volumes:
      - ./scripts/restore_from_backup.sh:/docker-entrypoint-initdb.d/restore_from_backup.sh
      - ./dump:/dump
    restart: unless-stopped

