version: '3'

services:
  avalon:
    build: .
    environment:
      DB_URL: mongodb://mongo:27017
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
      - 6001:6001
    restart: unless-stopped
    command: npm start

  mongo:
    image: mongo:4.2
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example